# Use the latest LTS version of Node.js
FROM node:20-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy package.json and package-lock.json
COPY package*.json ./
 
# Install dependencies
RUN npm install
 
# Copy the rest of your application files
COPY . .
 
# Build the React app
RUN npm run build
 
# Install serve globally
RUN npm install -g serve
 
# Expose port 80
EXPOSE 3001
 
# Serve the production build
CMD ["npm", "start"]
