services:
  portal:
    build: .
    ports:
      - "80:3001"
    volumes:
     - .:/app
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start
    networks:
      - hajki_shared_network

networks:
  hajki_shared_network:
    external: true