name: Deploy Backend to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/tamarabolmanac/hajki-portal:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 4️⃣ Deploy na tvoj server
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/hajki
            docker login ghcr.io -u tamarabolmanac -p ${{ secrets.GHCR_PAT }}
            docker-compose pull frontend
            docker-compose up -d frontend
            docker image prune -f
